spring:
  cache:
    type: redis
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  config:
    import:
      - config/application-dev.yml
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
logging:
  level:
    org:
      springframework:
#        batch: DEBUG
        orm:
#          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

#      카카오 페이
common:
  data:
    kakao: KakaoAK 79fd132c770be75df16bbafdcfe48463 //for test
    success: https://www.nfteam008.com/order/success
    cancel: https://www.nfteam008.com/order/cancel
    fail: https://www.nfteam008.com/order/fail